In [1]:
import numpy as np

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(-8, 25, 3)

array([-8, -5, -2,  1,  4,  7, 10, 13, 16, 19, 22])

In [10]:
np.arange(start=2, stop=-10, step=-2,)

array([ 2,  0, -2, -4, -6, -8])

In [14]:
np.arange(27).reshape([3, 9]).reshape([3, 3, 3])

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [28]:
np.random.random((10,)).reshape([5, 2])

array([[0.40454038, 0.234946  ],
       [0.20817701, 0.83487925],
       [0.90554538, 0.84266725],
       [0.85641657, 0.49895534],
       [0.46558035, 0.70302799]])

In [30]:
np.random.seed(10)
np.random.randint(50, 80, (4, 3, 3))

array([[[59, 79, 54],
        [65, 50, 67],
        [77, 78, 75]],

       [[79, 66, 79],
        [67, 76, 58],
        [59, 50, 60]],

       [[58, 72, 54],
        [69, 66, 54],
        [65, 61, 72]],

       [[74, 61, 76],
        [51, 58, 54],
        [64, 67, 69]]])

In [31]:
np.random.seed(10)
np.random.randint(50, 80, (4, 3, 3)).flatten()

array([59, 79, 54, 65, 50, 67, 77, 78, 75, 79, 66, 79, 67, 76, 58, 59, 50,
       60, 58, 72, 54, 69, 66, 54, 65, 61, 72, 74, 61, 76, 51, 58, 54, 64,
       67, 69])

In [33]:
np.arange(30).reshape((3, 10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])