In [1]:
import numpy as np

## 1. Calculating Total Revenue

In [3]:
prices = np.array([19.99, 29.99, 14.99, 9.99, 24.99])
prices

array([19.99, 29.99, 14.99,  9.99, 24.99])

In [4]:
quantities = np.array([10, 5, 8, 12, 3])
quantities

array([10,  5,  8, 12,  3])

In [7]:
revenue_per_product = prices * quantities
revenue_per_product

array([199.9 , 149.95, 119.92, 119.88,  74.97])

In [9]:
total_revenue = np.sum(revenue_per_product)
total_revenue

664.62

## 2. Analyzing Blog Post Stats

In [11]:
viems = np.array([1000, 500, 800, 1200, 300, 600])
viems

array([1000,  500,  800, 1200,  300,  600])

In [12]:
max_viems = np.max(viems)
max_viems

1200

In [13]:
min_viems = np.min(viems)
min_viems

300

In [16]:
average_viems = np.round(np.mean(viems), 2)
average_viems

733.33

In [17]:
total_viems = np.sum(viems)
total_viems

4400

## 3. Splitting Order into Batches

In [21]:
order_ids = np.array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008])
order_ids

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008])

In [22]:
batches = np.split(order_ids, 4)
batches

[array([1001, 1002]),
 array([1003, 1004]),
 array([1005, 1006]),
 array([1007, 1008])]

In [27]:
for i, batch in enumerate(batches):
    print(f'Batch num: {i}')
    print("First el in the batch: ", batch[0])
    print("Second el in the batch: ", batch[1])
    print()

Batch num: 0
First el in the batch:  1001
Second el in the batch:  1002

Batch num: 1
First el in the batch:  1003
Second el in the batch:  1004

Batch num: 2
First el in the batch:  1005
Second el in the batch:  1006

Batch num: 3
First el in the batch:  1007
Second el in the batch:  1008



## 4. Categorizing Product Ratings

In [28]:
ratings = np.array([4.5, 3.2, 2.8, 5.0, 4.1, 3.9, 2.5, 4.7])
ratings

array([4.5, 3.2, 2.8, 5. , 4.1, 3.9, 2.5, 4.7])

In [31]:
positive_ratings = ratings[ratings >= 4.0]
positive_ratings

array([4.5, 5. , 4.1, 4.7])

In [32]:
negative_ratings = ratings[ratings < 4.0]
negative_ratings

array([3.2, 2.8, 3.9, 2.5])

## 5. Calculate Total and Average quantities sold

In [42]:
# Each column is specific product (4 products)
# Each row is specific order (2 orders)
order_quantities = np.array([[5, 3, 2, 7], [10, 6, 3, 9]])
order_quantities

array([[ 5,  3,  2,  7],
       [10,  6,  3,  9]])

In [43]:
# Quantities of the sale per product
total_quantities_sold = np.sum(order_quantities, axis=0)
total_quantities_sold

array([15,  9,  5, 16])

In [44]:
# Quantities of the sale per order
total_products_per_order = np.sum(order_quantities, axis=1)
total_products_per_order

array([17, 28])

In [47]:
# Average quantities per product across all orders
average_quantities_sold = np.mean(order_quantities, axis=0)
average_quantities_sold

array([7.5, 4.5, 2.5, 8. ])

## 6. Calculate Average product Rating and Maximum rating per Category

In [49]:
# Each row is one product
# Each product is rated in 4 categories
product_ratings = np.array([
    [4.5, 3.2, 2.5, 5.0],
    [4.3, 3.0, 1.0, 4.8],
    [2.0, 3.6, 4.7, 0.5]
])
product_ratings

array([[4.5, 3.2, 2.5, 5. ],
       [4.3, 3. , 1. , 4.8],
       [2. , 3.6, 4.7, 0.5]])

In [54]:
# Average rating in each category
average_rating_per_category = np.mean(product_ratings, axis=0)
average_rating_per_category

array([3.6       , 3.26666667, 2.73333333, 3.43333333])

In [56]:
# Average rating for each product
average_rating_per_product = np.mean(product_ratings, axis=1)
average_rating_per_product

array([3.8  , 3.275, 2.7  ])

In [58]:
# Maximum rating in each category
max_rating_per_category = np.max(product_ratings, axis=0)
max_rating_per_category

array([4.5, 3.6, 4.7, 5. ])

In [59]:
# Minimum rating for each product
min_rating_per_product = np.min(product_ratings, axis=1)
min_rating_per_product

array([2.5, 1. , 0.5])

## 7. Generation of the sample stock data

In [60]:
companies = ['Google', 'Microsoft', 'Apple']
days = ['Mon 1 April', 'Tue 2 April']
price_types = ['Open', 'Close', 'High', 'Low']

In [63]:
np.random.seed(1)
stock_prices = np.round(np.random.random((len(companies), len(days), len(price_types))), 3)
stock_prices

array([[[0.417, 0.72 , 0.   , 0.302],
        [0.147, 0.092, 0.186, 0.346]],

       [[0.397, 0.539, 0.419, 0.685],
        [0.204, 0.878, 0.027, 0.67 ]],

       [[0.417, 0.559, 0.14 , 0.198],
        [0.801, 0.968, 0.313, 0.692]]])

In [64]:
stock_prices.shape

(3, 2, 4)

In [66]:
for index_axis_0, company in enumerate(companies):
    print(f'Stock prices for the {company}:')
    for index_axis_1, day in enumerate(days):
        print(f'Day: {day}')
        for index_axis_2, price_type in enumerate(price_types):
            print(f'{price_type} Price: {stock_prices[index_axis_0, index_axis_1, index_axis_2]}')
        print()
    print()

Stock prices for the Google:
Day: Mon 1 April
Open Price: 0.417
Close Price: 0.72
High Price: 0.0
Low Price: 0.302

Day: Tue 2 April
Open Price: 0.147
Close Price: 0.092
High Price: 0.186
Low Price: 0.346


Stock prices for the Microsoft:
Day: Mon 1 April
Open Price: 0.397
Close Price: 0.539
High Price: 0.419
Low Price: 0.685

Day: Tue 2 April
Open Price: 0.204
Close Price: 0.878
High Price: 0.027
Low Price: 0.67


Stock prices for the Apple:
Day: Mon 1 April
Open Price: 0.417
Close Price: 0.559
High Price: 0.14
Low Price: 0.198

Day: Tue 2 April
Open Price: 0.801
Close Price: 0.968
High Price: 0.313
Low Price: 0.692


